---
title: "numeric_eda"
author: "Tianshu Liu"
date: "2022-10-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r import}
library(tidyverse)

weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")
  ) %>%
  select(name, id, everything())
```

```{r counting}
# Counting 
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n()
  )

weather_df %>%
  count(name, month)

# don't use table!
weather_df %>%
  pull(month) %>%
  table()
```

```{r distinct_counting}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_dist = n_distinct(date)   # count how many dates each month has
  )

```

 
```{r 2*2_table}
# generate a tidy table
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n())

# pivot_wider => un-tidy
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(
    n_obs = n()
  ) %>%
  pivot_wider(
    names_from = cold,
    values_from = n_obs
  )

# janitor::tabyl
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

```{r funcs_in_summ}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp),
    median_tmax = median(tmax, na.rm = TRUE)
  )

weather_df %>%
  group_by(name, month) %>%
  summarize(across(tmin:prcp, mean))

weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point() +
  geom_line() 

weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE) # no na.rm => not continuous
  ) %>%
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 2) # use 'kable' to show
```

```{r centered}
weather_df %>%
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>%
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
  geom_point()
```

```{r lagged_observations}
weather_df %>%
  group_by(name) %>%
  mutate(
    yesterday_tmax = lag(tmax),
    tmax_change = tmax - yesterday_tmax
  ) %>%
  summarise(
    sd_tmax_change = sd(tmax_change, na.rm = TRUE)
  )
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(
    tmax_rank = min_rank(desc(tmax))
  ) %>%
  filter(tmax_rank < 4) %>%
  arrange(name, month, tmax_rank)
```



